# 5. Baby steps with neural networks (perceptrons and backpropagation)

### 5.1.3 Detour through bias

In [1]:
import numpy as np

example_input = [1, .2, .1, .05, .2]
example_weights = [.2, .12, .4, .6, .90]

input_vector = np.array(example_input)
weights = np.array(example_weights)
bias_weight = .2

activation_level = np.dot(input_vector, weights) +\
    (bias_weight * 1)
activation_level

0.6740000000000002

In [2]:
threshold = 0.5

if activation_level >= threshold:
    perceptron_output = 1
else:
    perceptron_output = 0
perceptron_output

1

In [3]:
expected_output = 0
new_weights = []

for i, x in enumerate(example_input):
    new_weights.append(weights[i] + (expected_output - perceptron_output) * x)
    
weights = np.array(new_weights)

example_weights

[0.2, 0.12, 0.4, 0.6, 0.9]

In [4]:
new_weights

[-0.8, -0.08000000000000002, 0.30000000000000004, 0.5499999999999999, 0.7]

In [5]:
sample_data = [[0, 0], # False, True
               [0, 1], # False, True
               [1, 0], # True, False
               [1, 1]] # True, True

expected_results = [0, # (False OR False) gives False
                    1, # (False OR True) gives True
                    1, # (True OR False) gives True
                    1] # (True OR True) gives True

activation_threshold = 0.5

In [6]:
from random import random
import numpy as np

weights = np.random.random(2)/1000 # SWmall random float 0 < w < 0.001
weights

array([0.00083483, 0.00015488])

In [7]:
bias_weight = np.random.random() / 1000
bias_weight

0.00045227435607033686

In [8]:
for idx, sample in enumerate(sample_data):
    input_vector = np.array(sample)
    activation_level = np.dot(input_vector, weights) +\
        (bias_weight * 1)
    if activation_level > activation_threshold:
        perceptron_output = 1
    else:
        perceptron_output = 0
    
    print('Predicted: {}'.format(perceptron_output))
    print('Expected:  {}'.format(expected_results[idx]))
    print()

Predicted: 0
Expected:  0

Predicted: 0
Expected:  1

Predicted: 0
Expected:  1

Predicted: 0
Expected:  1



In [9]:
for iteration_num in range(5):
    correct_answers = 0
    for idx, sample in enumerate(sample_data):
        input_vector = np.array(sample)
        activation_level = np.dot(input_vector, weights) +\
            (bias_weight * 1)
        
        if activation_level > activation_threshold:
            perceptron_output = 1
        else:
            perceptron_output = 0
            
        if perceptron_output == expected_results[idx]:
            correct_answers += 1
            
        new_weights = []
        for i, x in enumerate(sample):
            new_weights.append(weights[i] + (expected_results[idx] -\
                                             perceptron_output) * x)
            
        bias_weight = bias_weight + ((expected_results[idx] -\
                                      perceptron_output) * 1)
        
        weights = np.array(new_weights)
        
    print('{} correct answers out of 4, for iteration {}'\
          .format(correct_answers, iteration_num))

3 correct answers out of 4, for iteration 0
2 correct answers out of 4, for iteration 1
3 correct answers out of 4, for iteration 2
4 correct answers out of 4, for iteration 3
4 correct answers out of 4, for iteration 4


### 5.1.7. Keras: Neural networks in Python

In [10]:
# The base Keras model class
from keras.models import Sequential

# The basic layer of the network
# Dense is a fully-connected set of neurons
from keras.layers import Dense, Activation

# Get stochastic gradient descent, though there are others
# from keras.optimizers import SGD
from tensorflow.keras.optimizers import SGD

2022-05-27 15:18:21.581059: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-27 15:18:21.581109: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [11]:
# Our examples of exclusive OR.
# x_train is sample data
# y_train the expected outcome for example
x_train = np.array([[0, 0],
                    [0, 1],
                    [1, 0],
                    [1, 1]])
y_train = np.array([[0],
                    [1],
                    [1],
                    [0]])

In [13]:
model = Sequential()

# Add a fully connected hidden layer with 10 neurons
# The input shape is the shape of an individual sample vector
# This is only necessary in the first layer, any additional
# layers will calculate the shape automatically by the definition
# of the model up to that point

num_neurons = 10
model.add(Dense(num_neurons, input_dim=2))
model.add(Activation('tanh'))

# The output layer one neuron to output 0 or 1 
model.add(Dense(1))
model.add(Activation('sigmoid'))
print(model.summary())

2022-05-27 15:37:40.663318: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-05-27 15:37:40.666007: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-05-27 15:37:40.669686: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c79cc515617c): /proc/driver/nvidia/version does not exist
2022-05-27 15:37:40.696220: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 activation (Activation)     (None, 10)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
 activation_1 (Activation)   (None, 1)                 0         
                                                                 
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________
None


In [14]:
sgd = SGD(lr=0.1)
model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])

/opt/conda/lib/python3.9/site-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


In [15]:
print(model.predict(x_train))

[[0.5       ]
 [0.70282114]
 [0.4780121 ]
 [0.6556174 ]]


In [17]:
# Here is where we train the model
model.fit(x_train, y_train,
          epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 500ms/step - loss: 0.7125 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 6ms/step - loss: 0.7096 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 9ms/step - loss: 0.7070 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 10ms/step - loss: 0.7046 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 9ms/step - loss: 0.7025 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 7ms/step - loss: 0.7005 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 12ms/step - loss: 0.6987 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 7ms/step - loss: 0.6971 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 8ms/step - loss: 0.6956 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 0.6942 - accuracy: 0.5000
Epoch 11/100
1/1 [=======

In [18]:
model.predict_classes(x_train)

AttributeError: 'Sequential' object has no attribute 'predict_classes'

In [24]:
# predict_x=model.predict(x_train) 
# classes_x=np.argmax(predict_x,axis=1)
# classes_x

(model.predict(x_train) > 0.5).astype("int32")

array([[0],
       [1],
       [0],
       [1]], dtype=int32)

In [20]:
model.predict(x_train)

array([[0.41877836],
       [0.5740105 ],
       [0.48513466],
       [0.53442   ]], dtype=float32)

In [25]:
import h5py

# And then we save the structure and learned weights for later use
model_structure = model.to_json()
with open("basic_model.json", "w") as json_file:
    json_file.write(model_structure)

model.save_weights("basic_weights.h5")
print('Model saved.')

Model saved.
